apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-webapp
  name: go-webapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-webapp
    spec:
      containers:
        - image: katnip/go-webapp:latest
          imagePullPolicy: Always
          name: golang-webapp
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: config-vol
            mountPath: /trawler/config.yaml
            subPath: config.yaml
      volumes:
        - name:  config-vol
          configMap:
            name: auth-config
      dnsPolicy: ClusterFirst
