apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-webapp
  namespace: default
spec:
  rules:
    - host: test.trawler.sh
      http:
        paths:
          - backend:
              service: 
                name: go-webapp
                port:
                  number: 8080
            pathType: "Prefix"
            path: "/"