{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "trawler-webapp.serviceAccountName" . }}
  labels:
{{ include "trawler-webapp.labels" . | indent 4 }}
{{- end -}}
